pyodbc.cpython-37m-aarch64-linux-gnu.so,sha256=AWO16Z9iHVAj6JNhXZ04R7i22s_lwIfxE44OBfv_0Io,989496
pyodbc.pyi,sha256=JWNpdgmrxhNioTjW6OoAEcXELcGZobcMYzKtYlcJRuY,32320
pyodbc-4.0.38.dist-info/WHEEL,sha256=XucsZnoHuNCWn8fvv-NIdwNfG_W7e9Qj8D7iyIsD9T8,152
pyodbc-4.0.38.dist-info/LICENSE.txt,sha256=mFnIV3DJG3hmsPdpyTjjbWTQJgFBtSm5R7Tq2WiD6rQ,868
pyodbc-4.0.38.dist-info/RECORD,,
pyodbc-4.0.38.dist-info/METADATA,sha256=EjZZ8cmsdLrMbWGabwt6HcQGnUcZ89VyEbCiebo_njY,3160
pyodbc-4.0.38.dist-info/top_level.txt,sha256=Rb69vS-SNN_Bfh99vX7eCcvEAJoyzowG3u4R7W36Flw,8
